#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function usage {
    echo "Usage: $0 <port>"
    echo "       Receives datagrams on <port> and prints"
    echo "       sequence numbers to stdout"
    exit 1
}

[[ $# -ne 1 ]] && usage

echo "Receiving datagrams on port $1"
echo "Hit Ctrl-C to terminate..."

${SCRIPTDIR}/lib/recvdatagrams $1 10
